####################################
##     Phantom Toggle Config      ##
####################################


# In normal minecraft, what determines when phantoms spawn is when the time since you last rested exceeds 3 in-game days
# This is tracked in each player's statistics as TIME_SINCE_REST

# This plugin, periodically resets your TIME_SINCE_REST statistic when you set phantom spawns to be disabled
# The timer for that reset is set by this config option
restTimeResetTimer: 1200 # seconds
#       1200 seconds is the default, this is 20 minutes or 1 in-game day
#       3600 seconds (3 in-game days) is the longest you'd want to set this, since Phantoms spawn after 3 in-game days of not sleeping.

# This decides what the plugin does with your TIME_SINCE_REST statistic when you enable / disable phantom spawns
statHandlingMode: track
#       track : tracks the time since you actually last rested, and puts that value back when you turn phantom spawns back on
#       pause : when you disable phantom spawns, pauses your time since rest statistic and will resume from there when you turn spawns back on
#       reset : when turning spawns back on, starts counting time since rest from that time, starting from 0 from that moment, like you just rested




# -------------- #
# MESSAGE CONFIG #
# -------------- #

#   colors and basic text formatting can be in the forms
#     - &c        where c is a chat formatting character
#     - &#aabbcc  where aabbcc is a hex color

textHeader: "&r[&#485791Phantom&#21ae06Toggle&r]"
#       can be used in other text options as %textHeader%

textReload: "%textHeader% Config Reloaded"

textConfigChanged: '%textHeader% Config for %option% set to &d&l%value%&r, file updated'
#       additional values here are %option% and %value%

textPhantomsDisabled: "%textHeader% Your phantom spawns have been &l&cdisabled"
textPhantomsAlreadyDisabled: "%textHeader% Your phantom spawns are &lalready &r&cdisabled"

textPhantomsEnabled: "%textHeader% Your phantom spawns have been &l&aenabled"
textPhantomsAlreadyEnabled: "%textHeader% Your phantom spawns are &lalready &r&aenabled"