name: PhantomToggle
main: io.github.runcows.phantomtoggle.PhantomToggle
version: 1.0.0
api-version: 1.13
author: runcows

commands:
    phantoms:
        description: toggles phantom spawning on or off per player
        usage: /phantoms [on/off]
        permission: PhantomToggle.use
    phantomToggle:
        description: admin level control over the plugin
        usage: /phantomToggle [reload/config/help]
        permission: PhantomToggle.admin

permissions:
    use:
        description: Allows you to use the command /phantoms
        default: true
    admin:
        description: Allows you to use /phantom Toggle
        default: op